### ISSUE TITLE
Question about your AOC 2022 Day 16 Solution

### ISSUE THREAD

**Issue by steve-thousand** [TimHuisman1703/AdventOfCode#1]
I discovered your solution while looking for more efficient approaches than mine. Yours is very fast and concise, and though it works for my puzzle input as well, something about it seemed problematically and I wonder if you can comment.

In [this bit of code ](https://github.com/TimHuisman1703/AdventOfCode/blob/master/2022/Day%2016/aoc16_1.py#L33-L36)you make use of a sort of "visited" nodes to reduce the frontier space with each step. In this case, two paths taken are considered to be equal if you have arrived at the same valve at the same time with the same pressure rate. Combine that with the use of the heap and it guarantees that the first path added to the set (and therefore not skipped) is the path that has relieved the most pressure.

This seems like it will definitely prune suboptimal paths for that time step. However, is it guaranteed to produce the optimal path for later time steps? I have been trying to think of a scenario where two paths have arrived at the same location at the same time with the same rate but that further traversal of those paths would produce different outcomes. For instance, if 2 paths have reached the same valve but from opposite directions.

**Comment by TimHuisman1703** [comment]
Hi there,

You are completely correct! My approach of using `(pos, curr_rate)` as a "unique" identifier for a certain state is not guaranteed to result in an optimal value, as it will prune away many states with an equal flow rate and human position, but with a different set of valves turned on. It could be that one of these seemingly-equal-but-not-really states would actually lead to a better result, which would in turn be ignored by my code.
However, my priority was not to make code that works for any possible input, but to make code that worked for _my_ input at the time, and since I was rushing for a leaderboard position and wanted to go back to bed as soon as possible (the puzzles release at 6AM in my timezone), I decided to take the risk and prune violently. To my relief, this worked!
